os: linux

dist: bionic

language: shell

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - curl
      - gnupg
      - pkg-config

jobs:
  include:
  - stage: style_check
    script: pre-commit run -a --show-diff-on-failure
    before_install:
      - pip install identify==1.5.10
      - pip install pre-commit==1.20.0
      - sudo apt install clang-format-7
  - stage: unit_tests
    script: export ROS_DISTRO=melodic && bazel test //flow_ros/test/...
    before_install:
    - curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
    - echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
    - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
    - sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
    - curl -sSL 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xC1CF6E31E6BADE8868B172B4F42ED6FBAB17C654' | sudo apt-key add -
    - sudo apt update && sudo apt install bazel ros-melodic-ros-base ros-melodic-rosbag ros-melodic-class-loader
